// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMy7hvKa2xwV0x4TcZrxwoFsIDrWRcjXc',
    appId: '1:179222988612:web:e27c45f4fa74baedacb911',
    messagingSenderId: '179222988612',
    projectId: 'my-consumer-rating',
    authDomain: 'my-consumer-rating.firebaseapp.com',
    storageBucket: 'my-consumer-rating.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy6vc6UG3NXam2IWZY4sS_PMp2VNdd52o',
    appId: '1:179222988612:android:3e8d0acb3ea83ac9acb911',
    messagingSenderId: '179222988612',
    projectId: 'my-consumer-rating',
    storageBucket: 'my-consumer-rating.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXmsuoP5fuUYIvoaJ6DdAvdfalGshHPs',
    appId: '1:179222988612:ios:5aaa111d03e82838acb911',
    messagingSenderId: '179222988612',
    projectId: 'my-consumer-rating',
    storageBucket: 'my-consumer-rating.appspot.com',
    iosBundleId: 'com.thrivehub.analytics',
  );
}
